name: deploy-jupyter-book

on:
    push:
        branches:
            - main

# This job installs dependencies, build the book, and pushes it to personal pages
jobs:
    deploy-book:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Install dependencies
            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  pip install jupyter-book
            # Build the book
            - name: Build the book
              run: |
                  jupyter-book build notebooks
            # Push the book's HTML to personal pages
            - name: GitHub Pages action
              uses: peaceiris/actions-gh-pages@v3.5.9
              env:
                PERSONAL_TOKEN: ${{ secrets.DOC_DEPLOY_SECRET }}
              with:
                  github_token: ${{ env.PERSONAL_TOKEN }}
                  publish_dir: notebooks/_build/html
                  external_repository: timtreis/timtreis.github.io
                  publish_branch: docs
                  commit_message: "Deploy Jupyter Book"
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"